[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "flask-socketio>=5.5.1",
    "numpy>=2.2.2",
    "opencv-python>=4.11.0.86",
]
